### ISSUE TITLE
Nav and header + paragraph aren't going side by side for the navigation

### ISSUE THREAD

**Issue by Sophia-Villamayor** [ltw-webdesign-2/modularity-mindfulness#1]
@mackenzierose 
I'm not sure as to what I might be missing. I'd like the navigation sit on the right side, while the header and paragraph sit on the left side in one row.

<img width="582" alt="Screen Shot 2020-09-21 at 4 40 00 PM" src="https://user-images.githubusercontent.com/54897840/93818998-1c7c7a80-fc29-11ea-84c1-8774c0cdcd49.png">

**Comment by MacKenzieRose** [comment]
@Sophia-Villamayor I'll take a look; can you close this issue, and make an issue on your forked repository? This is actually the original assignment, and not your copy, which you can find here: https://github.com/Sophia-Villamayor/modularity-mindfulness
